// Auth

export const REGISTER_USER = 'REGISTER_USER';
export const GET_USER = 'GET_USER';
export const SET_USER_LOGIN = 'SET_USER_LOGIN';
export const EDIT_USER = 'EDIT_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SET_NATIONAL_CODE = 'SET_NATIONAL_CODE';
export const LOADING_USER_START = 'LOADING_USER_START';
export const GET_ORDERS = 'GET_ORDERS';
export const GET_SALE_LIST = 'GET_SALE_LIST';
export const GET_PRODUCT_LIST_DATA = 'GET_PRODUCT_LIST_DATA';
export const GET_HOME_PAGE_DATA = 'GET_HOME_PAGE_DATA';
export const GET_DIAGRAM_PAGE_DATA = 'GET_DIAGRAM_PAGE_DATA';
export const GET_SALETYPES = 'GET_SALETYPES';
export const GET_COMPANIES = 'GET_COMPANIES';
export const GET_COMPANY_SALES = 'GET_COMPANY_SALES';
export const GET_BANKS = 'GET_BANKS';
export const GET_PROVINCES = 'GET_PROVINCES';
export const GET_CITIES = 'GET_CITIES';

export const LOGIN_USER = 'LOGIN_USER';
export const LOADING_USER = 'LOADING_USER';
export const LOADING_USER_FINISH = 'LOADING_USER_FINISH';
export const LOADING_CARS = 'LOADING_CARS';
export const LOADING_CARS_FINISH = 'LOADING_CARS_FINISH';
export const LOADING_ORDERS = 'LOADING_ORDERS';
export const LOADING_ORDERS_FINISH = 'LOADING_ORDERS_FINISH';

// for Diesel
export const GET_SALE_DETAIL = 'GET_SALE_DETAIL';
export const GET_AGENCIES = 'GET_AGENCIES';
export const GET_AGENCIES_FOR_SALE = 'GET_AGENCIES_FOR_SALE';
export const GET_PSPS = 'GET_PSPS';

export const LOADING_ORDER_DETAIL = 'LOADING_ORDER_DETAIL';
export const LOADING_ORDER_DETAIL_FINISH = 'LOADING_ORDER_DETAIL_FINISH';
export const LOADING_AGANCY = 'LOADING_AGANCY';
export const LOADING_AGANCY_FINISH = 'LOADING_AGANCY_FINISH';
export const LOADING_PSP = 'LOADING_PSP';
export const LOADING_PSP_FINISH = 'LOADING_PSP_FINISH';
export const LOADING_COMMIT_ORDER = 'LOADING_COMMIT_ORDER';
export const LOADING_COMMIT_ORDER_FINISH = 'LOADING_COMMIT_ORDER_FINISH';
export const LOADING_PRODUCT_LIST_DATA = 'LOADING_PRODUCT_LIST_DATA';
export const LOADING_PRODUCT_LIST_DATA_FINISH =
  'LOADING_PRODUCT_LIST_DATA_FINISH';

export const SET_OTP_COUNTER = 'SET_OTP_COUNTER';
export const REMOVE_OTP_COUNTER = 'REMOVE_OTP_COUNTER';

export const GET_PRODUCTS_SLIDER_DATA = 'GET_PRODUCTS_SLIDER_DATA';

export const LOADING_DIAGRAM_PAGE_START = 'LOADING_DIAGRAM_PAGE_START';
export const LOADING_DIAGRAM_PAGE_FINISH = 'LOADING_DIAGRAM_PAGE_FINISH';

export const LOADING_HOME_PAGE_START = 'LOADING_HOME_PAGE_START';
export const LOADING_HOME_PAGE_FINISH = 'LOADING_HOME_PAGE_FINISH';

export const LOADING__ANNOUNCEMENTS_START = 'LOADING__ANNOUNCEMENTS_START';
export const LOADING__ANNOUNCEMENTS_FINISH = 'LOADING__ANNOUNCEMENTS_FINISH';
export const GET_ANNOUNCEMENTS = 'GET_ANNOUNCEMENTS';

export const LOADING_SEND_SMS_START = 'LOADING_SEND_SMS_START';
export const LOADING_SEND_SMS_FINISH = 'LOADING_SEND_SMS_FINISH';

export const LOADING_PRODUCT_DETAILS_START = 'LOADING_PRODUCT_DETAILS_START';
export const LOADING_PRODUCT_DETAILS_FINISH = 'LOADING_PRODUCT_DETAILS_FINISH';
export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';

export const GET_FACTOR = 'GET_FACTOR';
export const LOADING_SIGN_CONTRACT_START = 'LOADING_SIGN_CONTRACT_START';
export const LOADING_SIGN_CONTRACT_FINISH = 'LOADING_SIGN_CONTRACT_FINISH';
export const LOADING_GET_CONTRACT_START = 'LOADING_GET_CONTRACT_START';
export const LOADING_GET_CONTRACT_FINISH = 'LOADING_GET_CONTRACT_FINISH';
